version: "3.8"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    command: --tlsverify --http-api-token wathdaksncjpkawopsfgasd --http-api-metrics
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/animo/certs/docker-ms/:/etc/ssl/docker
    environment:
      - DOCKER_HOST=tcp://192.168.1.168:2376
      - DOCKER_CERT_PATH=/etc/ssl/docker